add support for bullmq
bee-queue/arena pull request #251
Opened 2020-10-17 17:50 UTC by gtpan77

Support for [bullmq](https://github.com/taskforcesh/bullmq)

issue: #248 

Pending changes -
@types/bull-arena in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

2020-10-20 07:04 UTC, gtpan77 commented
@skeggse, please review this PR.

2020-10-20 18:17 UTC, gtpan77 commented
[DefinitelyTyped/pull/48886](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48886)

2020-10-20 18:32 UTC, skeggse approved these changes

2020-10-20 18:34 UTC, skeggse requested changes
We'll need to actually use the `BullMQ` constructor over [here](https://github.com/bee-queue/arena/blob/2a268c3d8fc6a799126669a8fdd77815b0dc72e8/src/server/queue/index.js#L79-L96), I think.

https://github.com/bee-queue/arena/blob/2a268c3d8fc6a799126669a8fdd77815b0dc72e8/src/server/queue/index.js#L79-L96

2020-10-21 18:50 UTC, gtpan77 commented
I'll submit request changes within two days

2020-10-25 16:52 UTC, gtpan77 commented on src/server/views/helpers/queueHelpers.js
>      const stats = _.pickBy(queue.client.serverInfo, (value, key) =>
@skeggse, How is this field `queue.client.serverInfo` getting set?

I written simple code using `Bull` to understand how is it getting set but getting this error - `Property serverInfo does not exist on type Redis`
```
const client = await bullQueues.testQueue.client;
console.log(await client.info());
console.log(bullQueues.testQueue.client.serverInfo);
```

2020-10-26 19:30 UTC, jameschensmith commented on src/server/views/helpers/queueHelpers.js
>      const stats = _.pickBy(queue.client.serverInfo, (value, key) =>
Hey @gtpan77. Not sure if this helps, but [ioredis](https://github.com/luin/ioredis) appears to set `serverInfo` [in its connection handler](https://github.com/luin/ioredis/blob/v4.19.0/lib/redis/event_handler.ts#L87). Hope this helps! I've been wanting to use Bee Queue with Bull MQ for a while now. Appreciate your work on this!

2020-11-01 16:56 UTC, gtpan77 commented on src/server/views/helpers/queueHelpers.js
>      const stats = _.pickBy(queue.client.serverInfo, (value, key) =>
Thanks @jameschensmith, type definition of ioredis doesn't have serverInfo set as a member variable. I was testing my changes on typescript project so couldn't find the issue because I heavily relies on type definitions.
This code is working when I define client as any variable.
```
const client: any = await bullQueues.testQueue.client;
console.log(await client.info());
console.log(client.serverInfo);
```

2020-11-01 19:39 UTC, skeggse approved these changes
Seems fine to me, though I don't know whether there are additional places we might need to add bullmq support. I think it's probably best to label this as preliminary support for bullmq, and we'll get feedback if there are missing features.

We'll also want to document usage in the README - if you're able, I'd be happy to accept a PR that does that.

2020-11-01 19:39 UTC, merged

2020-11-01 19:41 UTC, beequeueci commented
:tada: This PR is included in version 3.4.0 :tada:

The release is available on:
- [GitHub release](https://github.com/bee-queue/arena/releases/tag/v3.4.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/bull-arena/v/3.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-11-02 06:01 UTC, gtpan77 commented
Thanks @skeggse, Yeah still there is a more to add for bullmq support. It will be my pleasure to contribute toward document usage.