Refresh page when adding a new job in dashboard
bee-queue/arena pull request #324
Opened 2021-02-17 04:12 UTC by roggervalf

When we add a new job and close the message of Job successfully added, we currently have to refresh the page manually to see the current state of that created job. This PR tries to handle this.

2021-02-17 23:54 UTC, bradvogel commented
This doesn't seem like something that should be added to arena generically, right? Some folks might want to add jobs in quick succession without the refresh

2021-02-18 01:37 UTC, roggervalf commented
> This doesn't seem like something that should be added to arena generically, right? Some folks might want to add jobs in quick succession without the refresh

Thank you @bradvogel I didn't consider that case, I could remove that part, what do you think in the button message change depending on hide prop?

2021-02-18 01:40 UTC, bradvogel commented
Yup that looks fine

2021-02-18 01:47 UTC, roggervalf commented
Thank you, comments are addressed

2021-02-18 14:03 UTC, bradvogel requested changes

2021-02-18 14:03 UTC, bradvogel commented on public/dashboard.js
> +    const shouldHide = addJobText !== 'Add Job';
I can't get this to work. My repro steps:

1. Run the example queue from PR https://github.com/bee-queue/arena/pull/326
![image](https://user-images.githubusercontent.com/821706/108366942-ef77c800-71c6-11eb-92c5-e72115ec3044.png)
2. Click the "Add Job" button.

Expected result: the button changes to "Cancel"
Actual result: the button doesn't change:
![image](https://user-images.githubusercontent.com/821706/108367062-0c140000-71c7-11eb-9686-349073b501f6.png)

2021-02-18 15:30 UTC, roggervalf commented on public/dashboard.js
> +    const shouldHide = addJobText !== 'Add Job';
Thank you @bradvogel, I could try your example and fix this condition, please take a look :eyes:

2021-02-18 21:26 UTC, bradvogel approved these changes
Reviewed and tested.

2021-02-18 21:26 UTC, merged

2021-02-18 21:28 UTC, beequeueci commented
:tada: This PR is included in version 3.7.1 :tada:

The release is available on:
- [GitHub release](https://github.com/bee-queue/arena/releases/tag/v3.7.1)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/bull-arena/v/3.7.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: