Retry bulk delayed jobs
bee-queue/arena pull request #330
Opened 2021-02-24 02:03 UTC by roggervalf

In order to trigger delayed jobs in bulk action.

2021-03-01 15:33 UTC, bradvogel commented
Are you sure it's safe to retry delayed jobs in all both Bull and Bee Queue? In looking at Bee Queue's code, it looks like it expects the job to be in the failed state.

2021-03-02 03:31 UTC, roggervalf commented
> Are you sure it's safe to retry delayed jobs in all both Bull and Bee Queue? In looking at Bee Queue's code, it looks like it expects the job to be in the failed state.

Thank you @bradvogel for clarify this for Bee Queue, I was considering Bull, I added a condition to show this button only with Bull. Please when you have some time give a second look :eyes:

2021-03-02 04:14 UTC, roggervalf commented on example/index.js
> +// const Bull = require('bull');
I added Bull in example and comment those lines, so people could try bull by commenting Bee and use Bull if they want, what do you think about this?

2021-03-02 22:19 UTC, bradvogel requested changes

2021-03-02 22:19 UTC, bradvogel commented on example/index.js
> +// const Bull = require('bull');
Mind splitting it out to a different file? Perhaps bee.js and bull.js. That'll be more maintainable in the long run, despite the redundancy in the files today.

2021-03-02 22:19 UTC, bradvogel commented on src/server/views/dashboard/templates/queueJobsByState.hbs
> +    {{#if (or (eq state 'failed') (and (eq state 'delayed') (eq queueType 'bull')))}}
There are already variables in this file for `disablePagination` and `disableOrdering`, so what do you think about using `{{#unless disableRetry}}` here for consistency? Then you won't need this complex logic in the template file - you can push it into the server-side JS file.

2021-03-02 23:46 UTC, roggervalf commented on src/server/views/dashboard/templates/queueJobsByState.hbs
> +    {{#if (or (eq state 'failed') (and (eq state 'delayed') (eq queueType 'bull')))}}
sure, I updated the PR with the requested changes. Tyty

2021-03-02 23:55 UTC, bradvogel approved these changes

2021-03-02 23:55 UTC, bradvogel commented on example/README.md
> +`npm start:bee`
neat!

2021-03-02 23:55 UTC, merged

2021-03-02 23:56 UTC, beequeueci commented
:tada: This PR is included in version 3.10.0 :tada:

The release is available on:
- [GitHub release](https://github.com/bee-queue/arena/releases/tag/v3.10.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/bull-arena/v/3.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: