Fix retry bulk action
bee-queue/arena pull request #334
Opened 2021-03-04 00:24 UTC by roggervalf

Retry bulk button is throwing an error because the action is not the correct one as in delayed status is sending remove only as action, now it handles the retry action too.

2021-03-04 15:25 UTC, roggervalf commented
@bradvogel could you please give some :eyes: on this PR when have some free time?

2021-03-05 22:00 UTC, bradvogel requested changes

2021-03-05 22:00 UTC, bradvogel commented on src/server/views/api/bulkAction.js
> +            ? fetchedJobs.map((job) => Queues.set(queue, job.data, job.name))
is this Bull specific?

2021-03-07 00:42 UTC, roggervalf commented on package.json
> +    "jsoneditor": "^9.2.0",
you are right, I couldn't find a reference, also trying the example without it and they are working. Tyty

2021-03-07 00:49 UTC, roggervalf commented on src/server/views/api/bulkAction.js
> +            ? fetchedJobs.map((job) => Queues.set(queue, job.data, job.name))
I'm seeing that this logic is for both cases https://github.com/bee-queue/arena/blob/master/src/server/views/api/jobRetry.js#L18, but in case of bulkAction for retry action is only allowed for Bull https://github.com/bee-queue/arena/blob/master/src/server/views/dashboard/queueJobsByState.js#L126 in delayed state. What do you think about it?

2021-03-07 14:51 UTC, bradvogel commented on src/server/views/api/bulkAction.js
> +            ? fetchedJobs.map((job) => Queues.set(queue, job.data, job.name))
When testing locally with Bee, I don't see jobs retrying. My repro steps:
1. Pull code from https://github.com/bee-queue/arena/pull/337 locally along with this PR
2. Run `npm run start:bee` from `/examples`
3. Create a few jobs in the UI:
![image](https://user-images.githubusercontent.com/821706/110243895-5d8fef00-7f2a-11eb-837e-39422a85b30c.png)
4. After a few seconds, about half of those jobs will be failed. Select them and click Retry. Refresh the page to show the latest job state.
![image](https://user-images.githubusercontent.com/821706/110243927-81533500-7f2a-11eb-88db-49637cd02ebe.png)

Expected result: those jobs are put back in the 'waiting' state and one is put in 'active'
Actual result: nothing happens. Those jobs stay in 'failed.

2021-03-07 19:44 UTC, roggervalf commented on src/server/views/api/bulkAction.js
> +            ? fetchedJobs.map((job) => Queues.set(queue, job.data, job.name))
thank you @bradvogel, now it should work. Also I add same example in bull file to try

2021-03-07 23:27 UTC, bradvogel approved these changes
tested locally and approved

2021-03-07 23:27 UTC, bradvogel commented on example/bull.js
> +  const queue = new Bull('name_of_my_queue', {
thanks!

2021-03-07 23:27 UTC, merged

2021-03-07 23:28 UTC, beequeueci commented
:tada: This PR is included in version 3.11.0 :tada:

The release is available on:
- [GitHub release](https://github.com/bee-queue/arena/releases/tag/v3.11.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/bull-arena/v/3.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: