Fix performance job details
bee-queue/arena pull request #341
Opened 2021-03-11 02:07 UTC by roggervalf

2021-03-11 02:25 UTC, roggervalf commented
Please @bradvogel when you have some free time, give some :eyes: on this PR

2021-03-11 17:53 UTC, bradvogel requested changes
How do I see the logs locally? I tried running `npm run start:bull` in the examples folder, added a job, and let it complete. I opened the direct link to the job (http://localhost:4735/Queue%20Server%201/name_of_my_queue/3) and didn't see "Logs" in the UI

2021-03-11 17:53 UTC, bradvogel commented on src/server/views/partials/dashboard/jobDetails.hbs
> +    {{moment (add (getDelay this) (getTimestamp this) ) "llll"}}
minor thing: it'd be cleaner for getDelay to internalize the math to add the delay. It's a bit confusing to have logic implemented in the template.

2021-03-11 17:53 UTC, bradvogel commented on src/server/views/helpers/handlebars.js
> +    if (job.timestamp) {
Small nitpick: This would be a slightly cleaner implementation:

```
  getTimestamp(job) {
    // Bull
    if (job.timestamp) {
      return job.timestamp;
    }

    // Bee
    if (job.options && job.options.timestamp) {
      return job.options.timestamp;
    }
  },
```

2021-03-11 17:53 UTC, bradvogel commented on src/server/views/helpers/handlebars.js
> +    return job.options ? job.options.delay : undefined;
See below - I would use getTimestamp() directly in this method in order to keep the business logic out of the template.

2021-03-11 19:31 UTC, roggervalf commented on src/server/views/helpers/handlebars.js
> +    return job.options ? job.options.delay : undefined;
sure, I could refactor it in my last commit tyty

2021-03-11 19:32 UTC, roggervalf commented
> How do I see the logs locally? I tried running `npm run start:bull` in the examples folder, added a job, and let it complete. I opened the direct link to the job (http://localhost:4735/Queue%20Server%201/name_of_my_queue/3) and didn't see "Logs" in the UI

I added a log example in bull example file, when getting into delayed job should appear it in the standalone page now

2021-03-12 00:50 UTC, bradvogel approved these changes

2021-03-12 00:50 UTC, merged

2021-03-12 00:51 UTC, beequeueci commented
:tada: This PR is included in version 3.15.0 :tada:

The release is available on:
- [GitHub release](https://github.com/bee-queue/arena/releases/tag/v3.15.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/bull-arena/v/3.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-18 11:05 UTC, anuragagarwal561994 commented
Hello @bradvogel I guess instead of completely disabling this feature we can provide this as an option to the user.
Some of us don't have thousand jobs and more to that if the pagination settings are under control like on one page if we display only 10-20 jobs then it should not make such difference.

2021-12-20 15:21 UTC, bradvogel commented
Yes, agreed. I'll accept a PR to add an option