feat: add optional custom css
bee-queue/arena pull request #347
Opened 2021-03-25 16:33 UTC by evolkmann

Allows users to host their own stylesheet to customize the appearance.

- - - - - -

As this is my first interaction in this project, I want to take the chance to say thank you, it is very useful for us!

2021-03-30 15:35 UTC, bradvogel requested changes
Thanks for the contribution! Just a few comments.

2021-03-30 15:35 UTC, bradvogel commented on example/bee.js
> +      customCssPath: 'https://example.com/custom-arena-styles.css',
mind removing this from the example so it doesn't 404?

2021-03-30 15:35 UTC, bradvogel commented on example/bull.js
> +      customCssPath: 'https://example.com/custom-arena-styles.css',
this too

2021-03-30 15:35 UTC, bradvogel commented on README.md
> +  customCssPath: 'https://example.com/custom-arena-styles.css',
Add to the `following optional parameters` section in the readme also.

2021-03-31 07:00 UTC, evolkmann commented
@bradvogel Thanks for your feedback! I agree, it should not be in the examples with that invalid URL 👍🏻

2021-03-31 11:55 UTC, bradvogel approved these changes

2021-03-31 11:55 UTC, merged