Promote delayed job in bull
bee-queue/arena pull request #353
Opened 2021-03-31 00:42 UTC by roggervalf

This PR is for adding a button to promote delayed jobs for bull. Also I added an example for bullmq (note: this is just a simple example)

2021-03-31 00:48 UTC, roggervalf commented
@bradvogel please, when you get some time for some :eyes:

2021-04-02 18:39 UTC, bradvogel requested changes
Can you please include a test plan? Something like:
1. Run `npm run start:bullmq` from examples
2. Open job...
3. Click promote

I'm not sure where the

2021-04-02 18:39 UTC, bradvogel commented on example/package.json
>      "test": "echo \"Error: no test specified\" && exit 1"
Also, add a note to the example/readme about this command

2021-04-02 18:39 UTC, bradvogel commented on example/bullmq.js
> +  const delayedJob = await queue.add('delayed', {}, { delay: 60 * 1000 });
This job isn't processing for me locally after a minute. Is it for you?

2021-04-02 18:39 UTC, bradvogel commented on public/dashboard.js
> +    const r = window.confirm(`Retry job #${jobId} in queue "${queueHost}/${queueName}"?`);
Is 'Retry' the right verb here? The job could have just been created and never tried before, right?

2021-04-02 19:46 UTC, roggervalf commented on public/dashboard.js
> +    const r = window.confirm(`Retry job #${jobId} in queue "${queueHost}/${queueName}"?`);
ops, let me change this

2021-04-02 19:54 UTC, roggervalf commented on example/bullmq.js
> +  const delayedJob = await queue.add('delayed', {}, { delay: 60 * 1000 });
Yes, I'm because there is not a worker to process the job, but this example is only for trying delayed jobs for now :(

2021-04-02 19:55 UTC, roggervalf commented on example/package.json
>      "test": "echo \"Error: no test specified\" && exit 1"
sure, let me do it

2021-04-02 19:56 UTC, bradvogel commented on example/bullmq.js
> +  const delayedJob = await queue.add('delayed', {}, { delay: 60 * 1000 });
Mind adding a worker just so all the examples function the same way. For example, the Bee queue example processes the delayed job.

2021-04-02 19:57 UTC, roggervalf commented on example/bullmq.js
> +  const delayedJob = await queue.add('delayed', {}, { delay: 60 * 1000 });
let me look how to add it, still pretty new in bullmq xd

2021-04-02 19:59 UTC, bradvogel commented on example/bullmq.js
> +  const delayedJob = await queue.add('delayed', {}, { delay: 60 * 1000 });
yup probably something like this https://docs.bullmq.io/guide/jobs/delayed

2021-04-02 20:10 UTC, roggervalf commented on example/bullmq.js
> +  const delayedJob = await queue.add('delayed', {}, { delay: 60 * 1000 });
Yes, thank you I added it in last commit :rocket:

2021-04-02 20:19 UTC, roggervalf commented on .github/pull_request_template.md
> +
this file was getting an error by prettier so now it is fine

2021-04-05 13:54 UTC, bradvogel requested changes

2021-04-05 13:54 UTC, bradvogel commented on .github/pull_request_template.md
> +
You can revert this change. I fixed prettier in another PR: https://github.com/bee-queue/arena/pull/359/files#diff-b640b344ee7f3f03d2a443795a5d0708ef50e2e6e34214109ab2aad13ad6ba98R4

2021-04-05 13:54 UTC, bradvogel commented on example/bullmq.js
> +  const delayedJob = await queue.add('delayed', {}, { delay: 60 * 1000 });
I see the job moving to 'waiting' but it never moves to 'active'. Can you have the example process the job fully and fail it 50%, so it's consistent with the other queue examples?

![image](https://user-images.githubusercontent.com/821706/113581088-a653ca00-95f4-11eb-9b57-bf944b62a843.png)

2021-04-05 15:00 UTC, roggervalf commented on example/bullmq.js
> +  const delayedJob = await queue.add('delayed', {}, { delay: 60 * 1000 });
sure, I added it in last commit

2021-04-05 15:14 UTC, roggervalf commented on .github/pull_request_template.md
> +
sure I made a push force for it

2021-04-05 15:41 UTC, roggervalf commented
@bradvogel thank you for your review, I could addressed your comments in last version

2021-04-05 19:36 UTC, bradvogel approved these changes

2021-04-05 19:37 UTC, merged

2021-04-05 19:38 UTC, beequeueci commented
:tada: This PR is included in version 3.19.0 :tada:

The release is available on:
- [GitHub release](https://github.com/bee-queue/arena/releases/tag/v3.19.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/bull-arena/v/3.19.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: