Adding external links into nav
bee-queue/arena pull request #356
Opened 2021-04-02 00:36 UTC by roggervalf

2021-04-02 00:45 UTC, roggervalf commented
@bradvogel please when you get a chance, some :eyes: in this PR

2021-04-02 00:57 UTC, roggervalf commented on example/bull.js
> +      externalLinks: [{ link: 'https://www.google.com/', text: 'google' }],
I added it for now, just to see in it with an example, after this PR is checked I could delete it

2021-04-02 00:58 UTC, roggervalf commented on src/server/app.js
> -  app.locals.customCssPath = config.customCssPath;
From docs said that this should come from listenOpts param, not from config that is for queue configuration

2021-04-02 19:02 UTC, bradvogel commented on README.md
> +- `externalLinks` - an array of external links to be included in nav (default: null)
Can you share more about your use case for this? I'm concerned this is a "slippery slope" and there will be an explosion of different parameters to try to customize the UX. What we might need is some way to override the internal HTML templates that Arena uses.

2021-04-02 19:36 UTC, roggervalf commented on README.md
> +- `externalLinks` - an array of external links to be included in nav (default: null)
sure, in my team we have some other projects related to queues that we would like to add in this nav for easy access when navigating between projects, could it be possible to have this in or something that I can change?

2021-04-02 19:40 UTC, roggervalf commented on README.md
> +    customCssPath: 'https://example.com/custom-arena-styles.css',
I have a doubt here, in readme appears:
![Selection_018](https://user-images.githubusercontent.com/14021523/113448350-44f7e500-93c1-11eb-9347-d7352d98bd46.png)
that customCssPath should be in listenOpts, not in queue config param :thinking: maybe also that part should be changed too :thinking:

2021-04-02 19:51 UTC, bradvogel commented on README.md
> +    customCssPath: 'https://example.com/custom-arena-styles.css',
Great catch. That was another bug in the readme. I fixed via a force push to https://github.com/bee-queue/arena/pull/359/files

2021-04-02 19:55 UTC, bradvogel commented on README.md
> +- `externalLinks` - an array of external links to be included in nav (default: null)
What if we added a `customJsPath` parameter and you used it to write the links in using client-side JS? My thinking is that a `customJsPath` parameter would provide a lot more flexibility to customize anything.

2021-04-02 20:22 UTC, roggervalf commented on README.md
> +    customCssPath: 'https://example.com/custom-arena-styles.css',
nice let me revert these related changes

2021-04-02 21:47 UTC, roggervalf commented on README.md
> +- `externalLinks` - an array of external links to be included in nav (default: null)
Sure let me change this

2021-04-02 22:04 UTC, roggervalf commented
in this PR I tried to handle the styled error with pr template https://github.com/bee-queue/arena/pull/353, this is why is failing

2021-04-05 12:52 UTC, bradvogel requested changes

2021-04-05 12:52 UTC, bradvogel commented on example/bull.js
> +      customJsPath: 'example.js',
When I run the Bull example (via `npm run start:bull` from the examples dir) and navigate into a queue, I get the following 404 error:

![image](https://user-images.githubusercontent.com/821706/113575527-fb3f1280-95eb-11eb-9140-2ed43300086c.png)

2021-04-05 12:52 UTC, bradvogel commented on README.md
> +  customJsPath: 'https://example.com/custom-arena-js.js',
looks like there's a merge conflict with master

2021-04-05 15:09 UTC, roggervalf commented on example/bull.js
> +      customJsPath: 'example.js',
Good catch, I fixed it in last commit

2021-04-05 15:35 UTC, roggervalf commented on README.md
> +  customJsPath: 'https://example.com/custom-arena-js.js',
I could fixed in last commits. Tyty

2021-04-05 19:28 UTC, bradvogel approved these changes

2021-04-05 19:28 UTC, merged

2021-04-05 19:29 UTC, beequeueci commented
:tada: This PR is included in version 3.18.0 :tada:

The release is available on:
- [GitHub release](https://github.com/bee-queue/arena/releases/tag/v3.18.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/bull-arena/v/3.18.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: