add pause/resume button to bull queues
bee-queue/arena pull request #375
Opened 2021-04-30 10:00 UTC by kwkr

#### Changes Made
Added `Pause/Resume` button to the queue details view.

#### Potential Risks
I can't think of any.

#### Test Plan
To be discussed

#### Checklist

- [ ] I've increased test coverage
- [x] Since this is a public repository, I've checked I'm not publishing private data in the code, commit comments, or this PR.

2021-04-30 10:02 UTC, kwkr commented
This is only an idea for the feature that would be really convenient to have. So far I'm really missing it and I have to do it using `Bull` library directly. I'm happy to know your opinion on this.

2021-05-04 16:19 UTC, bradvogel commented on src/server/views/helpers/queueHelpers.js
> +    return isPausedValue == 1;
use `===`

2021-05-04 16:22 UTC, bradvogel requested changes

2021-05-04 16:22 UTC, bradvogel commented on src/server/views/helpers/queueHelpers.js
> +    return isPausedValue == 1;
use `===`

2021-05-04 16:22 UTC, bradvogel commented on public/dashboard.js
> +    const r = window.confirm(
use a more descriptive variable name, eg `const response = `

2021-05-04 16:22 UTC, bradvogel commented on public/dashboard.js
> +    const r = window.confirm(
use a more descriptive variable name, eg `const response = `

2021-05-04 16:22 UTC, bradvogel commented on public/dashboard.js
> +          window.alert(`Queue "${queueHost}/${queueName} paused.`);
Do we need a second alert? The page refreshing and the button changing the 'resume' should be enough user feedback. What do you think?

2021-05-04 16:22 UTC, bradvogel commented on public/dashboard.js
> +          window.alert(`Queue "${queueHost}/${queueName} resumed.`);
same here - do we need the second alert?

2021-05-04 16:22 UTC, bradvogel commented
I reviewed this before it might have been ready. Please click Ready for Review when you'd like a second review.

2021-05-24 17:10 UTC, bradvogel commented
PR https://github.com/bee-queue/arena/pull/391 included this. Closing

2021-05-24 17:10 UTC, closed without merging