Fix handlebars and paused state
bee-queue/arena pull request #391
Opened 2021-05-21 03:06 UTC by roggervalf

#### Changes Made
This PR fixes handlebars vulnerability and I noticed that from bull, when entering to paused page is getting an error, so I fixed that issue too, as bullmq has paused state too, I also added it to it.
#### Potential Risks
Now we are allowed to enter to paused state page without errors

#### Test Plan
1.Go to example directory
2.Run: npm run start:bull
3.Enter to the queue and paused state, you should enter to that page without error
4.Same case for bullmq
#### Checklist

- [ ] I've increased test coverage
- [x] Since this is a public repository, I've checked I'm not publishing private data in the code, commit comments, or this PR.

2021-05-21 21:11 UTC, roggervalf commented
@bradvogel please when you get some change for some :eyes: on this pr

2021-05-24 17:09 UTC, bradvogel requested changes

2021-05-24 17:09 UTC, bradvogel commented on public/dashboard.js
> +      `Do you really want to pause the queue "${queueHost}/${queueName}"?`
```suggestion
      `Are you sure you want to pause the queue "${queueHost}/${queueName}"?`
```

2021-05-24 17:09 UTC, bradvogel commented on src/server/views/helpers/queueHelpers.js
> +  isPaused: async function (queue) {
When I run `npm run start:bee` in the examples folder and load http://localhost:4735/Queue%20Server%201/name_of_my_queue, I get the following error:
```
(node:44450) UnhandledPromiseRejectionWarning: TypeError: queue.isPaused is not a function
    at Object.isPaused (/Users/brad/dev/arena/src/server/views/helpers/queueHelpers.js:50:18)
    at handler (/Users/brad/dev/arena/src/server/views/dashboard/queueDetails.js:25:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

2021-05-24 17:09 UTC, bradvogel commented on public/dashboard.js
> +      `Do you want to resume the queue "${queueHost}/${queueName}"?`
```suggestion
      `Are you sure you want to resume the queue "${queueHost}/${queueName}"?`
```

2021-05-25 13:06 UTC, bradvogel commented
When you're ready for me to re-review, just click this button:
![image](https://user-images.githubusercontent.com/821706/119502950-78f3e480-bd38-11eb-8c70-e4f67df847cd.png)

2021-05-25 13:17 UTC, roggervalf commented
> When you're ready for me to re-review, just click this button:
> ![image](https://user-images.githubusercontent.com/821706/119502950-78f3e480-bd38-11eb-8c70-e4f67df847cd.png)
Thank you @bradvogeSorry for the delay

2021-05-25 13:18 UTC, roggervalf commented
Thank you @bradvogel, sorry for the delay

2021-05-25 13:36 UTC, bradvogel approved these changes
tested locally

2021-05-25 13:37 UTC, merged

2021-05-25 13:38 UTC, beequeueci commented
:tada: This PR is included in version 3.22.0 :tada:

The release is available on:
- [GitHub release](https://github.com/bee-queue/arena/releases/tag/v3.22.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/bull-arena/v/3.22.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: