Fix jobDetails: show progress for bee and bullmq
bee-queue/arena pull request #397
Opened 2021-06-04 04:42 UTC by roggervalf

#### Changes Made
This PR allows to see progress for bee and bullmq, at the pass it only shows progress for bull queue only, because in bullmq was showing undefined
#### Potential Risks
No potential risk
#### Test Plan
Please run the 3 examples:
1. npm run start:bee and open the job, after it completes the progress bar should be increased
2. npm run start:bull and open the job, after it completes the progress bar should be increased
3. npm run start:bullmq and open the job, after it completes the progress bar should be increased

#### Checklist

- [ ] I've increased test coverage
- [x] Since this is a public repository, I've checked I'm not publishing private data in the code, commit comments, or this PR.

2021-06-04 04:44 UTC, roggervalf commented
@bradvogel please when you get a chance, give some :eyes: on this PR

2021-06-04 17:53 UTC, bradvogel requested changes

2021-06-04 17:53 UTC, bradvogel commented on example/bee.js
I'm not able to get this to work.

When testing with `npm run start:bee` it shows 0% once the job is active:
![image](https://user-images.githubusercontent.com/821706/120843374-06ef7c80-c53c-11eb-8071-f569478c3595.png)

When testing with `npm run start:bull` it shows undefined for progress in the active job:
![image](https://user-images.githubusercontent.com/821706/120843306-f3441600-c53b-11eb-8667-48e1ac261a81.png)

The BullMQ example is the only one that works correctly:
![image](https://user-images.githubusercontent.com/821706/120843503-2edee000-c53c-11eb-83bf-67fffc9d3744.png)

2021-06-04 19:20 UTC, roggervalf commented on example/bee.js
hi @bradvogel, for bee, it is updated in succeeded state:
![Selection_030](https://user-images.githubusercontent.com/14021523/120851635-b6c5e980-c53e-11eb-8444-e28e2d6ce2b2.png)
For bull I found the issue, let me address it

2021-06-04 19:22 UTC, roggervalf commented
now for bull should appear:
![Selection_031](https://user-images.githubusercontent.com/14021523/120852781-47e99000-c540-11eb-8b0a-85f65bcd979f.png)

2021-06-07 18:12 UTC, roggervalf commented
> now for bull should appear:
> ![Selection_031](https://user-images.githubusercontent.com/14021523/120852781-47e99000-c540-11eb-8b0a-85f65bcd979f.png)

Please @bradvogel when you get a chance for some 👀

2021-06-07 23:09 UTC, bradvogel requested changes

2021-06-07 23:09 UTC, bradvogel commented on src/server/views/partials/dashboard/jobDetails.hbs
>  <h5>Progress</h5>
Are you sure "Progress" should now show up for bee queue?

2021-06-07 23:12 UTC, roggervalf commented on src/server/views/partials/dashboard/jobDetails.hbs
>  <h5>Progress</h5>
I'm not 100% aware how the progress is used in Bee, but I can just fix the progress for bullmq for now. Let me address it

2021-06-07 23:52 UTC, bradvogel commented
This looks fine, though the PR description doesn't match the implementation. Is the intent to ONLY show progress for Bull, and not show it for Bee and BullMQ?

2021-06-07 23:58 UTC, roggervalf commented
> This looks fine, though the PR description doesn't match the implementation. Is the intent to ONLY show progress for Bull, and not show it for Bee and BullMQ?

oh, I just put bullmq in the description because currently we could see the progress for bull, but when running bullmq example, it is showing undefined. Now it should show bullmq progress well

2021-06-08 00:10 UTC, bradvogel approved these changes
oh, I see now.

2021-06-08 00:10 UTC, merged

2021-06-08 00:11 UTC, beequeueci commented
:tada: This PR is included in version 3.24.1 :tada:

The release is available on:
- [GitHub release](https://github.com/bee-queue/arena/releases/tag/v3.24.1)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/bull-arena/v/3.24.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: