fix(job-details): encodeURI of job ID for URL
bee-queue/arena pull request #417
Opened 2021-07-02 02:56 UTC by olliechick

fixes #416

#### Changes Made

Added `encodeURI` to job's ID.

#### Checklist

- [ ] I've increased test coverage
- [x] Since this is a public repository, I've checked I'm not publishing private data in the code, commit comments, or this PR.

2021-07-02 12:49 UTC, bradvogel requested changes
mind updating the other places in this file where this.id is used in the URL?

2021-07-04 21:42 UTC, olliechick commented
> mind updating the other places in this file where this.id is used in the URL?

done ✅

2021-07-06 12:12 UTC, bradvogel approved these changes

2021-07-06 12:12 UTC, merged

2021-07-06 12:14 UTC, beequeueci commented
:tada: This PR is included in version 3.29.1 :tada:

The release is available on:
- [GitHub release](https://github.com/bee-queue/arena/releases/tag/v3.29.1)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/bull-arena/v/3.29.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: